```python
import os
import sqlite3

# Constants
DEFAULT_DB_NAME = "store.db"
DB_PATH_ENV_VAR = "DB_PATH"
DEFAULT_USER_ACTIVE_STATUS = 1
DEFAULT_ORDER_STATUS = "pending"
TABLE_USERS = "users"
TABLE_ORDERS = "orders"
COLUMN_ID = "id"
COLUMN_USERNAME = "username"
COLUMN_EMAIL = "email"
COLUMN_HASHED_PASSWORD = "hashed_password"
COLUMN_IS_ACTIVE = "is_active"
COLUMN_CREATED_AT = "created_at"
COLUMN_USER_ID = "user_id"
COLUMN_ITEMS = "items"
COLUMN_TOTAL = "total"
COLUMN_STATUS = "status"
DB_CONSTRAINT_CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP"
DB_CONSTRAINT_AUTOINCREMENT = "AUTOINCREMENT"
DB_CONSTRAINT_PRIMARY_KEY = "PRIMARY KEY"
DB_CONSTRAINT_UNIQUE = "UNIQUE"
DB_CONSTRAINT_NOT_NULL = "NOT NULL"
DB_CONSTRAINT_DEFAULT = "DEFAULT"
DB_CONSTRAINT_FOREIGN_KEY = "FOREIGN KEY"

_DB_PATH = os.environ.get(DB_PATH_ENV_VAR, DEFAULT_DB_NAME)
_conn: sqlite3.Connection | None = None


def get_connection() -> sqlite3.Connection:
    global _conn
    if _conn is None:
        _conn = sqlite3.connect(_DB_PATH, check_same_thread=False)
        _conn.row_factory = sqlite3.Row
        _bootstrap(_conn)
    return _conn


def _bootstrap(conn: sqlite3.Connection) -> None:
    conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_USERS} (
            {COLUMN_ID} INTEGER {DB_CONSTRAINT_PRIMARY_KEY} {DB_CONSTRAINT_AUTOINCREMENT},
            {COLUMN_USERNAME} TEXT {DB_CONSTRAINT_UNIQUE} {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_EMAIL} TEXT {DB_CONSTRAINT_UNIQUE} {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_HASHED_PASSWORD} TEXT {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_IS_ACTIVE} INTEGER {DB_CONSTRAINT_DEFAULT} {DEFAULT_USER_ACTIVE_STATUS},
            {COLUMN_CREATED_AT} TEXT {DB_CONSTRAINT_DEFAULT} {DB_CONSTRAINT_CURRENT_TIMESTAMP}
        );
        CREATE TABLE IF NOT EXISTS {TABLE_ORDERS} (
            {COLUMN_ID} INTEGER {DB_CONSTRAINT_PRIMARY_KEY} {DB_CONSTRAINT_AUTOINCREMENT},
            {COLUMN_USER_ID} INTEGER {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_ITEMS} TEXT {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_TOTAL} REAL {DB_CONSTRAINT_NOT_NULL},
            {COLUMN_STATUS} TEXT {DB_CONSTRAINT_DEFAULT} '{DEFAULT_ORDER_STATUS}',
            {COLUMN_CREATED_AT} TEXT {DB_CONSTRAINT_DEFAULT} {DB_CONSTRAINT_CURRENT_TIMESTAMP},
            {DB_CONSTRAINT_FOREIGN_KEY} ({COLUMN_USER_ID}) REFERENCES {TABLE_USERS}({COLUMN_ID})
        );
    """)
    conn.commit()
```